# Generated by Django 3.0.4 on 2020-03-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=255)),
                ('post_date', models.DateField()),
                ('post_content', models.TextField(max_length=255)),
            ],
        ),
    ]
