# Generated by Django 3.0.4 on 2020-03-16 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200316_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now_add='true', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
