# Generated by Django 3.0.4 on 2020-03-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200316_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='new_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title_name',
        ),
    ]
