# Generated by Django 3.0.4 on 2020-03-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200317_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_name',
            new_name='post_title',
        ),
    ]
