# Generated by Django 3.0.4 on 2020-03-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200317_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='new_title',
        ),
    ]
